# Sensors are gathering information about states and conditions.
#
# https://www.home-assistant.io/components/sensor/
#
# I still need to split this into single files
# sensor: !include_dir_list ../entities/sensors

sensor: !include ../sensors.yaml