- id: SetTheme
  alias: System - Set Theme
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: midnight-blue-round
    service: frontend.set_theme
  initial_state: true
- id: AllOutsideLightsOn
  alias: Lights - Turn ON All Outside Lights if any outside light is turned on
  trigger:
  - entity_id: light.outside_driveway_lights
    platform: state
    to: 'on'
  - entity_id: light.outside_cottage_back_door_light
    platform: state
    to: 'on'
  - entity_id: light.outside_cottage_front_stoep
    platform: state
    to: 'on'
  - entity_id: light.outside_flat_backdoor_light
    platform: state
    to: 'on'
  - entity_id: light.outside_play_area_lights
    platform: state
    to: 'on'
  - entity_id: light.outside_house_flood_light
    platform: state
    to: 'on'
  - entity_id: light.outside_carport_light
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data: {}
    entity_id: light.all_outside_lights
    service: light.turn_on
  initial_state: true
- id: OutsideLightsOffAfterRestart
  alias: Lights - Turn OFF outside lights if HA Starts
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:01:00
  - data: {}
    entity_id: light.all_outside_lights
    service: light.turn_off
  initial_state: true
- id: UpgradeAlertHA
  alias: Alert - Upgrade available - Home Assistant
  trigger:
  - entity_id: sensor.version_available
    platform: state
  condition:
  - condition: template
    value_template: "{{\n  states('sensor.version_available')\n  !=\n  states('sensor.version_current')\n\
      }}"
  action:
  - data_template:
      data:
        attachment:
          content-type: png
          url: https://gcswhassio.duckdns.org/local/images/package-up.png
      message: There is a Home Assistant upgrade pending! Version {{ states('sensor.version_available')
        }} just got released! Version {{ states('sensor.version_current') }} is currently
        installed.
      title: Upgrade time!
    service: notify.mobile_app_gregs_iphone_8_plus
  - data_template:
      message: There is a Home Assistant upgrade pending! Version {{ states('sensor.version_available')
        }} just got released! Version {{ states('sensor.version_current') }} is currently
        installed.
      notification_id: home_assistant_upgrade
      title: Upgrade time!
    service: persistent_notification.create
- id: PoolON
  alias: Pool Pump - Daily Timer ON
  trigger:
  - event: sunrise
    offset: 02:00:00
    platform: sun
  action:
  - entity_id: switch.tasmota_pool_pump
    service: switch.turn_on
  initial_state: true
- id: PoolOFF
  alias: Pool Pump - Daily timer OFF
  trigger:
  - event: sunset
    offset: -02:30:00
    platform: sun
  action:
  - entity_id: switch.tasmota_pool_pump
    service: switch.turn_off
  initial_state: true
- id: PoolOFFAfterPowerFailure
  alias: Pool Pump - Turn OFF if power comes on after 4pm
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - after: '16:00'
    before: 07:00
    condition: time
  action:
  - data: {}
    entity_id: switch.tasmota_pool_pump
    service: switch.turn_off
  initial_state: true
- id: MobileAppLightsOn
  alias: Lights - Turn ON all outside lights from actionable notification
  trigger:
  - event_data:
      actionName: TURN_ON_OUTSIDE_LIGHTS
    event_type: ios.notification_action_fired
    platform: event
  action:
  - entity_id: light.all_outside_lights
    service: light.turn_on
  initial_state: true
- id: MobileAppLightsOff
  alias: Lights - Turn OFF all outside lights from actionable notification
  trigger:
  - event_data:
      actionName: TURN_OFF_OUTSIDE_LIGHTS
    event_type: ios.notification_action_fired
    platform: event
  action:
  - entity_id: light.all_outside_lights
    service: light.turn_off
  initial_state: true
- id: MobileAppLightsToggle
  alias: Lights - TOGGLE All Outside Lights from actionable notification
  trigger:
  - event_data:
      actionName: TOGGLE_OUTSIDE_LIGHTS
    event_type: ios.notification_action_fired
    platform: event
  action:
  - entity_id: light.all_outside_lights
    service: light.toggle
  initial_state: true
- id: MobileAppLightsGate
  alias: Driveway Gate - Open/Close from actionable notification
  trigger:
  - event_data:
      actionName: OPEN_CLOSE_DRIVEWAY_GATE
    event_type: ios.notification_action_fired
    platform: event
  action:
  - entity_id: switch.gate_remote
    service: switch.toggle
  initial_state: true
- id: '20'
  alias: Actionable Notification  - Jenny Approaching Home
  trigger:
  - below: '750'
    entity_id: proximity.jenny_to_home
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ states.proximity.jenny_to_home.attributes.dir_of_travel
        == "towards" }}'
    - condition: state
      entity_id: device_tracker.life360_jenny
      state: moving
  action:
  - data:
      data:
        push:
          category: ARRIVING_HOME
      message: Approaching Home
    service: notify.mobile_app_gregs_iphone_8_plus
  initial_state: true
- id: OutsideLighstOffWhenLeaving
  alias: Lights - Turn Outside Lights OFF when leaving
  trigger:
  - entity_id: device_tracker.life360_jenny
    from: home
    platform: state
  - entity_id: device_tracker.life360_greg
    from: home
    platform: state
  - entity_id: device_tracker.life360_sally
    from: home
    platform: state
  condition: []
  action:
  - data: {}
    entity_id: light.all_outside_lights
    service: light.turn_off
- id: FlatHeaterOffWhenSallyLeaves
  alias: Heater - Turn OFF Flat Heater when Sally leaves in the morning
  trigger:
  - entity_id: device_tracker.life360_sally
    from: home
    platform: state
  condition:
  - after: 04:00
    before: '16:00'
    condition: time
  action:
  - data: {}
    entity_id: switch.flat_bedroom_heater
    service: switch.turn_off
- id: '1574517252030'
  alias: System - Start HomeKit
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 0:05
  - service: homekit.start
- id: timer_mainbed_fan
  alias: Fan Off Timer - Main Bedroom Fan
  trigger:
  - entity_id: fan.main_bedroom_fan
    for: 00:{{ states('input_number.main_bedroom_fan_timer') | int }}:00
    platform: state
    to: 'on'
  action:
  - entity_id: fan.main_bedroom_fan
    service: fan.turn_off
- id: timer_nursery_fan
  alias: Fan Off Timer - Nursery Fan
  trigger:
  - entity_id: fan.nursery_fan
    for: 00:{{ states('input_number.nursery_fan_timer') | int }}:00
    platform: state
    to: 'on'
  action:
  - entity_id: fan.nursery_fan
    service: fan.turn_off
- id: '1581163268118'
  alias: Alert - Upgrade available - HACS
  description: ''
  trigger:
  - above: '0'
    entity_id: sensor.hacs
    platform: numeric_state
  condition: []
  action:
  - data_template:
      data:
        attachment:
          content-type: png
          url: https://gcswhassio.duckdns.org/local/images/package-up.png
      message: There are HACS upgrades available!
      title: HACS Upgrades Available!
    service: notify.mobile_app_gregs_iphone_8_plus
  - data_template:
      message: There are HACS upgrades available!
      notification_id: hacs_upgrade
      title: HACS Upgrades Available!
    service: persistent_notification.create
- id: '1582284127172'
  alias: Geyser - Turn OFF Flat Geyser after power restore.
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:30:00
  - entity_id: switch.sonoff_1000878ab4
    service: switch.turn_off
- id: Corona Alert
  alias: Alert - Corona Stats
  trigger:
  - entity_id: sensor.south_africa_coronavirus_confirmed
    platform: state
  - entity_id: sensor.south_africa_coronavirus_deaths
    platform: state
  - entity_id: sensor.south_africa_coronavirus_recovered
    platform: state
  action:
  - data_template:
      data:
        attachment:
          content-type: png
          url: https://brands.home-assistant.io/coronavirus/logo.png
      message: South Africa COVID-19 Update. Confirmed Cases {{ states('sensor.south_africa_coronavirus_confirmed')
        }}, Current Cases {{ states('sensor.south_africa_coronavirus_current') }},
        Deaths {{ states('sensor.south_africa_coronavirus_deaths') }}, Recovered {{
        states('sensor.south_africa_coronavirus_recovered') }}.
      title: COVID-19
    service: notify.mobile_app_gregs_iphone_8_plus
  - data_template:
      data:
        attachment:
          content-type: png
          url: https://brands.home-assistant.io/coronavirus/logo.png
      message: South Africa COVID-19 Update. Confirmed Cases {{ states('sensor.south_africa_coronavirus_confirmed')
        }}, Current Cases {{ states('sensor.south_africa_coronavirus_current') }},
        Deaths {{ states('sensor.south_africa_coronavirus_deaths') }}, Recovered {{
        states('sensor.south_africa_coronavirus_recovered') }}.
      title: COVID-19
    service: notify.mobile_app_jenny_s_iphone_7_plus
