homeassistant:

  # Load packages
  packages: !include_dir_named yaml_configured_integrations

  ################################################################################
    
  # Customization file
  customize: !include customize.yaml

default_config:

# Fake Heater setup to send Temps to Google Home
climate: 
  - platform: generic_thermostat
    name: Pool Temp
    heater: input_boolean.fake_heater
    target_sensor: sensor.pool_temperature
  - platform: generic_thermostat
    name: Outside Temp
    heater: input_boolean.fake_heater
    target_sensor: sensor.outside_temperature
  - platform: generic_thermostat
    name: Flat Bedroom Temp
    heater: input_boolean.fake_heater
    target_sensor: sensor.flat_bedroom_temperature

# Fake Heater setup to send Temps to Google Home
input_boolean:
  fake_heater:
    name: Fake Heater
    initial: off

