esphome:
  name: nodemcu1
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
output:
  - platform: gpio
    pin: D5
    id: yellow_led
    
light:
  - platform: binary
    name: "Night Light Yellow"
    id: night_light_yellow
    output: yellow_led

    
binary_sensor:
  - platform: gpio
    pin: 
      number: D8
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    name: "Night Light Switch"
    on_press:
      then:
        - light.toggle: night_light_yellow
        

    
