esphome:
  name: nodemcu_roboguardintercept
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
