esphome:
  name: d1mini_roboguardintercept
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

  ap:
    ssid: d1mini_roboguardintercept
    password: !secret wifi_password
    
# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass

# web_server:
#   port: 80
  
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP      
    name: Beams 1
    device_class: motion
    filters:
      - delayed_off: 5s
    on_press:
      then:
        - switch.turn_on: beams1_out_sw
        - delay: 5s
        - switch.turn_off: beams1_out_sw
    
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: Beams 2
    device_class: motion
    filters:
      - delayed_off: 5s
    on_press:
      then:
        - switch.turn_on: beams2_out_sw
        - delay: 5s
        - switch.turn_off: beams2_out_sw
    
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: Beams 3
    device_class: motion
    filters:
      - delayed_off: 5s
    on_press:
      then:
        - switch.turn_on: beams3_out_sw
        - delay: 5s
        - switch.turn_off: beams3_out_sw
    
  - platform: gpio
    pin:
      number: GPIO16
      # mode: INPUT_PULLUP
    name: Beams 4
    device_class: motion
    filters:
      - delayed_off: 5s
    on_press:
      then:
        - switch.turn_on: beams4_out_sw
        - delay: 5s
        - switch.turn_off: beams4_out_sw
    
switch:
  - platform: gpio
    pin: D1
    # name: "Beams 1 Out Switch"
    id: beams1_out_sw
    
  - platform: gpio
    pin: D2
    # name: "Beams 2 Out Switch"
    id: beams2_out_sw
    
  - platform: gpio
    pin: D3
    # name: "Beams 3 Out Switch"
    id: beams3_out_sw
    
  - platform: gpio
    pin: D4
    # name: "Beams 4 Out Switch"
    id: beams4_out_sw

  