esphome:
  name: nodemculounge
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

  ap:
    ssid: nodemculounge
    password: !secret wifi_password
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  

sensor:
  - platform: dht
    pin: D3
    model: DHT11
    temperature:
      name: "Outside Temperature"
      accuracy_decimals: 0
    humidity:
      name: "Outside Humidity"
      accuracy_decimals: 0
    update_interval: 60s
    
  - platform: dht
    pin: D4
    model: DHT11
    temperature:
      name: "Lounge Temperature"
      accuracy_decimals: 0
    humidity:
      name: "Lounge Humidity"
      accuracy_decimals: 0
    update_interval: 60s

  - platform: adc
    pin: A0
    name: "Lounge Brightness"
    unit_of_measurement: '%'
    update_interval: 60s
    accuracy_decimals: 0
    filters:
      - multiply: 100

binary_sensor:
  - platform: gpio
    pin: 
      number: D7
    filters:
      - delayed_on: 100ms
      - delayed_off: 3s
    name: "Driveway Gate"
    device_class: garage_door

  - platform: gpio
    pin: 
      number: D8
#      mode: INPUT_PULLUP
#    filters:
#      - delayed_on: 100ms
#      - delayed_off: 100ms
    name: "Gate Bell 1"

switch:
  - platform: gpio
    id: relay
    pin: 
      number: D1
      inverted: yes
  - platform: template
    name: "Gate Remote"
    icon: "mdi:gate"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

