esphome:
  name: nodemcumainbed
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
sensor:
  - platform: dht
    pin: D2
    model: DHT11
    temperature:
      name: "Main Bedroom Temperature"
      accuracy_decimals: 0
    humidity:
      name: "Main Bedroom Humidity"
      accuracy_decimals: 0
    update_interval: 60s
    
  - platform: dht
    pin: D3
    model: DHT11
    temperature:
      name: "Nursery Temperature"
      accuracy_decimals: 0
    humidity:
      name: "Nursery Humidity"
      accuracy_decimals: 0
    update_interval: 60s
