esphome:
  name: nurserylamp_sonoffbasic
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

  ap:
    ssid: nurserylamp_sonoffbasic
    password: !secret wifi_password
    
# Enable logging
logger:


# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: nursery_lamp

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: nursery_lamp
    name: "Nursery Lamp"
    output: relay