esphome:
  name: outsideflatbackdoor_sonoffbasic
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

# Enable logging
logger:
  level: error

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: oustide_flat_backdoor_light

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: oustide_flat_backdoor_light
    name: "Outside Flat Back Door Light"
    output: relay