esphome:
  name: pool_sonoffth16
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks
  ap:
    ssid: pool_sonoffth16
    password: !secret esphomepass
    
# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Pool Pump"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
dallas:
  - pin: GPIO14

sensor:
  - platform: dallas
    address: 0xD9031841848FFF28
    name: "Pool Temperature"
