esphome:
  name: tv_led_esp01s
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid_not
  password: !secret wifi_password_not
  fast_connect: true
  # Enable fast_connect for hidden wifi networks

  ap:
    ssid: tv_led_esp01s
    password: !secret wifi_password
    

# Enable logging
logger:


# Enable Home Assistant API
api:
  password: !secret esphomepass

ota:
  password: !secret esphomepass
  
  
light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: GPIO2
    num_leds: 24
    rgb_order: BRG
    name: "TV LED"
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      # inverted: true
    name: "Sony TV Power Sensor"